/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Allan-Jay Branscombe (https://sketchfab.com/AllanJayBranscombe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-ready-canvas-painting-ee67515842ce4bc785dbbb86e6b39744
Title: Game Ready - Canvas Painting
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CanvasModel(props) {
    const { nodes, materials } = useGLTF('/assets/models/canvas/scene.gltf');
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.defaultMaterial.geometry}
                    material={materials.material}
                    rotation={[Math.PI / 2, 0, 0]}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/assets/models/canvas/scene.gltf');